name: Upload ROS Package

on:
  release:
    types: [released]

jobs:
  bloom-release:
    runs-on: ubuntu-latest

    steps:
      - name: bloom release
        uses: at-wat/bloom-release-action@v0
        with:
          ros_distro: rolling galactic foxy melodic noetic
          github_token_bloom: ${{ secrets.BLOOM_TOKEN }}
          github_user: pantor
          git_user: Lars Berscheid
          git_email: lars.berscheid@ruckig.com
          release_repository_push_url: https://github.com/${{ github.repository }}-release.git
          # open_pr: true
